/**
 * The MIT License (MIT)
 *
 * Copyright 2021 就眠儀式
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
import { IconName } from 'layui';

/**
 * 代码来源 Layui-Vue 项目
 * 2023-11-07 09:39:48
 * @see https://github.com/layui/layui-vue.git Layui-Vue
 * @see https://github.com/layui/layui-vue/blob/2.x/package/icons/src/iconfont/iconfont.ts Layui-vue icon 代码文件
 */
export default [
  { name: '实心', class: 'heart-fill' },
  { name: '空心', class: 'heart' },
  { name: '亮度/晴', class: 'light' },
  { name: '时间/历史', class: 'time' },
  { name: '蓝牙', class: 'bluetooth' },
  { name: '@艾特', class: 'at' },
  { name: '静音', class: 'mute' },
  { name: '录音/麦克风', class: 'mike' },
  { name: '密钥/钥匙', class: 'key' },
  { name: '礼物/活动', class: 'gift' },
  { name: '邮箱', class: 'email' },
  { name: 'RSS', class: 'rss' },
  { name: 'WiFi', class: 'wifi' },
  { name: '退出/注销', class: 'logout' },
  { name: 'Android 安卓', class: 'android' },
  { name: 'Apple IOS 苹果', class: 'ios' },
  { name: 'Windows', class: 'windows' },
  { name: '穿梭框', class: 'transfer' },
  { name: '客服', class: 'service' },
  { name: '减', class: 'subtraction' },
  { name: '加', class: 'addition' },
  { name: '滑块', class: 'slider' },
  { name: '打印', class: 'print' },
  { name: '导出', class: 'export' },
  { name: '列', class: 'cols' },
  { name: '退出全屏', class: 'screen-restore' },
  { name: '全屏', class: 'screen-full' },
  { name: '半星', class: 'rate-half' },
  { name: '星星-空心', class: 'rate' },
  { name: '星星-实心', class: 'rate-solid' },
  { name: '手机', class: 'cellphone' },
  { name: '验证码', class: 'vercode' },
  { name: '微信', class: 'login-wechat' },
  { name: 'QQ', class: 'login-qq' },
  { name: '微博', class: 'login-weibo' },
  { name: '密码', class: 'password' },
  { name: '用户名', class: 'username' },
  { name: '刷新-粗', class: 'refresh-three' },
  { name: '授权', class: 'auz' },
  { name: '左向右伸缩菜单', class: 'spread-left' },
  { name: '右向左伸缩菜单', class: 'shrink-right' },
  { name: '雪花', class: 'snowflake' },
  { name: '提示说明', class: 'tips' },
  { name: '便签', class: 'note' },
  { name: '主页', class: 'home' },
  { name: '高级', class: 'senior' },
  { name: '刷新', class: 'refresh' },
  { name: '刷新', class: 'refresh-one' },
  { name: '旗帜', class: 'flag' },
  { name: '主题', class: 'theme' },
  { name: '消息-通知', class: 'notice' },
  { name: '网站', class: 'website' },
  { name: '控制台', class: 'console' },
  { name: '表情-惊讶', class: 'face-surprised' },
  { name: '设置-空心', class: 'set' },
  { name: '模板', class: 'template-one' },
  { name: '应用', class: 'app' },
  { name: '模板', class: 'template' },
  { name: '赞', class: 'praise' },
  { name: '踩', class: 'tread' },
  { name: '男', class: 'male' },
  { name: '女', class: 'female' },
  { name: '相机-空心', class: 'camera' },
  { name: '相机-实心', class: 'camera-fill' },
  { name: '菜单-水平', class: 'more' },
  { name: '菜单-垂直', class: 'more-vertical' },
  { name: '金额-人民币', class: 'rmb' },
  { name: '金额-美元', class: 'dollar' },
  { name: '钻石-等级', class: 'diamond' },
  { name: '火', class: 'fire' },
  { name: '返回', class: 'return' },
  { name: '位置-地图', class: 'location' },
  { name: '办公-阅读', class: 'read' },
  { name: '调查', class: 'survey' },
  { name: '表情-微笑', class: 'face-smile' },
  { name: '表情-哭泣', class: 'face-cry' },
  { name: '购物车', class: 'cart-simple' },
  { name: '购物车', class: 'cart' },
  { name: '下一页', class: 'next' },
  { name: '上一页', class: 'prev' },
  { name: '上传-空心-拖拽', class: 'upload-drag' },
  { name: '上传-实心', class: 'upload' },
  { name: '下载-圆圈', class: 'download-circle' },
  { name: '组件', class: 'component' },
  { name: '文件-粗', class: 'file-b' },
  { name: '用户', class: 'user' },
  { name: '发现-实心', class: 'find-fill' },
  { name: 'loading', class: 'loading' },
  { name: 'loading', class: 'loading-one' },
  { name: '添加', class: 'add-one' },
  { name: '播放', class: 'play' },
  { name: '暂停', class: 'pause' },
  { name: '音频-耳机', class: 'headset' },
  { name: '视频', class: 'video' },
  { name: '语音-声音', class: 'voice' },
  { name: '消息-通知-喇叭', class: 'speaker' },
  { name: '删除线', class: 'fonts-del' },
  { name: '代码', class: 'fonts-code' },
  { name: 'HTML', class: 'fonts-html' },
  { name: '字体加粗', class: 'fonts-strong' },
  { name: '删除链接', class: 'unlink' },
  { name: '图片', class: 'picture' },
  { name: '链接', class: 'link' },
  { name: '表情-笑-粗', class: 'face-smile-b' },
  { name: '左对齐', class: 'align-left' },
  { name: '右对齐', class: 'align-right' },
  { name: '居中对齐', class: 'align-center' },
  { name: '字体-下划线', class: 'fonts-u' },
  { name: '字体-斜体', class: 'fonts-i' },
  { name: 'Tabs 选项卡', class: 'tabs' },
  { name: '单选框-选中', class: 'radio' },
  { name: '单选框-候选', class: 'circle' },
  { name: '编辑', class: 'edit' },
  { name: '分享', class: 'share' },
  { name: '删除', class: 'delete' },
  { name: '表单', class: 'form' },
  { name: '手机-细体', class: 'cellphone-fine' },
  { name: '聊天 对话 沟通', class: 'dialogue' },
  { name: '文字格式化', class: 'fonts-clear' },
  { name: '窗口', class: 'layer' },
  { name: '日期', class: 'date' },
  { name: '水 下雨', class: 'water' },
  { name: '代码-圆圈', class: 'code-circle' },
  { name: '轮播组图', class: 'carousel' },
  { name: '翻页', class: 'prev-circle' },
  { name: '布局', class: 'layouts' },
  { name: '工具', class: 'util' },
  { name: '选择模板', class: 'templeate-one' },
  { name: '上传-圆圈', class: 'upload-circle' },
  { name: '树', class: 'tree' },
  { name: '表格', class: 'table' },
  { name: '图表', class: 'chart' },
  { name: '图标 报表 屏幕', class: 'chart-screen' },
  { name: '引擎', class: 'engine' },
  { name: '下三角', class: 'triangle-d' },
  { name: '右三角', class: 'triangle-r' },
  { name: '文件', class: 'file' },
  { name: '设置-小型', class: 'set-sm' },
  { name: '减少-圆圈', class: 'reduce-circle' },
  { name: '添加-圆圈', class: 'add-circle' },
  { name: '404', class: 'not-found' },
  { name: '关于', class: 'about' },
  { name: '箭头 向上', class: 'up' },
  { name: '箭头 向下', class: 'down' },
  { name: '箭头 向左', class: 'left' },
  { name: '箭头 向右', class: 'right' },
  { name: '圆点', class: 'circle-dot' },
  { name: '搜索', class: 'search' },
  { name: '设置-实心', class: 'set-fill' },
  { name: '群组', class: 'group' },
  { name: '好友', class: 'friends' },
  { name: '回复 评论 实心', class: 'reply-fill' },
  { name: '菜单 隐身 实心', class: 'menu-fill' },
  { name: '记录', class: 'log' },
  { name: '图片-细体', class: 'picture-fine' },
  { name: '表情-笑-细体', class: 'face-smile-fine' },
  { name: '列表', class: 'list' },
  { name: '发布 纸飞机', class: 'release' },
  { name: '对 OK', class: 'ok' },
  { name: '帮助', class: 'help' },
  { name: '客服', class: 'chat' },
  { name: 'top 置顶', class: 'top' },
  { name: '收藏-空心', class: 'star' },
  { name: '收藏-实心', class: 'star-fill' },
  { name: '关闭-实心', class: 'close-fill' },
  { name: '关闭-空心', class: 'close' },
  { name: '正确', class: 'ok-circle' },
  { name: '添加-圆圈-细体', class: 'add-circle-fine' },

  { name: '帮助', class: 'help-circle' },
  { name: '感叹号', class: 'tips-fill' },
  { name: '测试', class: 'test' },
  { name: '清空删除', class: 'clear' },
  { name: '键盘', class: 'keyboard' },
  { name: '退格', class: 'backspace' },
  { name: '显示密码', class: 'show' },
  { name: '隐藏密码', class: 'hide' },
  { name: '错误', class: 'error' },
  { name: '成功', class: 'success' },
  { name: '疑问', class: 'question' },
  { name: '锁定', class: 'lock' },
  { name: '月亮', class: 'moon' },
  { name: 'Github', class: 'github' },
  { name: '禁用', class: 'disabled' },
  { name: 'Gitee', class: 'gitee' },
  { name: '闭眼', class: 'eye-invisible' },
  { name: '眼睛', class: 'eye' },
] as { name: string; class: IconName }[];
